[package]
name = "vls"
version = "0.5.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
termcolor = "1.4"
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5.0"
